### PR TITLE
- Added dependency on Eigen for basic vector math.

### PR DESCRIPTION
**Pull request by michaelplutovr**
- Added overlay sample based off of OverlayUser_Remote
- Adeed basic interaction tests via a naive intersection with the plane
  and a toggle
- added dependency on locating a xrloader lib for the sample.

### CODE REVIEW

**Comment by bradgrantham-lunarg** [comment]
When I build from this branch, I get 2>LINK : fatal error LNK1104: cannot open file '..\..\vendored\openxr_loader.lib'

I assume you want the developer to "mkdir vendored" and pull the loader lib into there.

How hard would it be to add a FindOpenXR or some such like FindFreeImage?  How do other OpenXR projects find and use the openxr package?

Or could you co-opt the OPENXR_SDK_SOURCE_ROOT stuff from api-layer/CMakeLists.txt?

**Comment by bradgrantham-lunarg** [comment]
I think I'm going to pull this now, but we should resolve the vendored loader issue.

**Comment by michaelplutovr** [comment]
Brad,

These slipped past my radar. adding a Find module for them seems like the
way to go, I can start work on a PR to patch that up Tomorrow. As a quick
stop gap to unify the way things are found I'll focus on a pr that co-opts
the OPENXR_SDK_SOURCE_ROOT.

**Comment by bradgrantham-lunarg** [comment]
Michael, a PR first that co-opts OPENXR_SDK_SOURCE_ROOT and then later one that adds a Find module would be great!  In the meantime I've made a vendored directory myself for my build, and figured as this approached release I'd come back around to this issue.

**Pull request merged**
